### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by evandroamparo** [digibart/upscuits#20]
I'm running Upscuits on my server and I'm getting wrong times. All the times in the log of last month are added with 6 hours. My timezone in UptimeRobot settings is correct (GMT -3).

I saw the times in `placeServer` function are parsed with "GMT+0300", but why?

**Comment by digibart** [comment]
Hm... you're right.

`GMT +3000` shoudn't be hardcoded, but should set with current users browsers timezone offset

**Comment by Monter** [comment]
Maybe get "showTimezone" from API? If user set the correct time zone in UptimeRobot configuration UptimeRobot widget will show the correct time for the event logs.

**Comment by evandroamparo** [comment]
Just removing `GMT +3000` from code is OK for me, but if the user's time zone is different from the server's time zone this can be a problem. @Monter's solutions may be the way.

**Comment by digibart** [comment]
guess there are three options:

1. show times in UTC. This is not uncommon in the _world of logging_, but is not so user friendly for the visitor 'cause he has to convert it to his/her local time
2. show in visitors timezone. Very friendly for the user.
3. use the timezone configured in Uptime (@monter's solution)

what do you guys prefer? (I tend to option 2 )

**Comment by Monter** [comment]
I choose the option, in which the time given in Upscuits is consistent with my time zone ;-)

**Comment by evandroamparo** [comment]
I choose option 2.

**Comment by Monter** [comment]
After this "fix" Upscuits show a wrong time in logs... No comment.
