### ISSUE TITLE
No new language in footer

### ISSUE THREAD

**Issue by Monter** [digibart/upscuits#22]
When I create a new language file based on a sample, and I put it in the appropriate folder of the language does not appear in the footer of the page as possible to choose. The list of available languages is hardcoded in index.html...

**Comment by digibart** [comment]
That's true. Because the `index.html` is static, no server side scripting like PHP or NodeJS is used. 

Keeping Upscuits static makes it easy to deploy it on most basic/cheap/simple shared webhosting.
